export type PageRoute = {
  key: string;
  title: string;
  path: string;
  apiModule?: string;
};

export const promotionalRoutes = [
  { key: 'home', title: 'Home', path: '/' },
  { key: 'features-overview', title: 'Features Overview', path: '/features' },
  { key: 'feature-whatsapp-automation', title: 'WhatsApp Automation Feature Page', path: '/features/whatsapp-automation' },
  { key: 'feature-ai-chatbot', title: 'AI Chatbot Feature Page', path: '/features/ai-chatbot' },
  { key: 'feature-workflow-automation', title: 'Workflow Automation Feature Page', path: '/features/workflow-automation' },
  { key: 'feature-shared-inbox', title: 'Shared Inbox Feature Page', path: '/features/shared-inbox' },
  { key: 'feature-knowledge-base', title: 'Knowledge Base Feature Page', path: '/features/knowledge-base' },
  { key: 'pricing', title: 'Pricing', path: '/pricing' },
  { key: 'compare-plans', title: 'Compare Plans', path: '/compare-plans' },
  { key: 'book-demo', title: 'Book Demo', path: '/book-demo' },
  { key: 'start-free-trial', title: 'Start Free Trial', path: '/start-free-trial' },
  { key: 'contact-sales', title: 'Contact Sales', path: '/contact-sales' },
  { key: 'usecase-customer-support', title: 'Use Case: Customer Support', path: '/use-cases/customer-support' },
  { key: 'usecase-lead-generation', title: 'Use Case: Lead Generation', path: '/use-cases/lead-generation' },
  { key: 'usecase-ecommerce-automation', title: 'Use Case: E-commerce Automation', path: '/use-cases/ecommerce-automation' },
  { key: 'usecase-appointment-booking', title: 'Use Case: Appointment Booking', path: '/use-cases/appointment-booking' },
  { key: 'usecase-education-coaching', title: 'Use Case: Education / Coaching', path: '/use-cases/education-coaching' },
  { key: 'documentation', title: 'Documentation', path: '/documentation' },
  { key: 'api-documentation', title: 'API Documentation', path: '/api-documentation' },
  { key: 'integration-guide', title: 'Integration Guide', path: '/integration-guide' },
  { key: 'blog-list', title: 'Blog List', path: '/blog' },
  { key: 'blog-detail', title: 'Blog Detail Page', path: '/blog/:slug' },
  { key: 'help-center-faq', title: 'Help Center / FAQ', path: '/help-center' },
  { key: 'terms-of-service', title: 'Terms of Service', path: '/terms-of-service' },
  { key: 'privacy-policy', title: 'Privacy Policy', path: '/privacy-policy' },
  { key: 'cookie-policy', title: 'Cookie Policy', path: '/cookie-policy' },
  { key: 'login', title: 'Login', path: '/login' },
  { key: 'register', title: 'Register', path: '/register' },
  { key: 'forgot-password', title: 'Forgot Password', path: '/forgot-password' },
  { key: 'reset-password', title: 'Reset Password', path: '/reset-password' },
  { key: 'email-verification', title: 'Email Verification', path: '/email-verification' },
] as const;
export const tenantRoutes = [
  { key: 'dashboard-overview', title: 'Dashboard Overview', path: '/app/dashboard', apiModule: 'analytics' },
  { key: 'conversations-list', title: 'Conversations List', path: '/app/conversations', apiModule: 'conversations' },
  { key: 'conversation-detail', title: 'Conversation Detail (Chat Interface)', path: '/app/conversations/:id', apiModule: 'messages' },
  { key: 'whatsapp-accounts-list', title: 'WhatsApp Accounts List', path: '/app/whatsapp/accounts', apiModule: 'whatsapp' },
  { key: 'connect-whatsapp-number', title: 'Connect WhatsApp Number', path: '/app/whatsapp/connect', apiModule: 'whatsapp' },
  { key: 'whatsapp-account-details', title: 'WhatsApp Account Details', path: '/app/whatsapp/accounts/:id', apiModule: 'whatsapp' },
  { key: 'template-management', title: 'Template Management', path: '/app/whatsapp/templates', apiModule: 'messages' },
  { key: 'message-logs', title: 'Message Logs', path: '/app/whatsapp/logs', apiModule: 'messages' },
  { key: 'ai-settings', title: 'AI Settings', path: '/app/ai/settings', apiModule: 'ai' },
  { key: 'ai-playground', title: 'AI Playground (Test AI)', path: '/app/ai/playground', apiModule: 'ai' },
  { key: 'ai-usage-token-analytics', title: 'AI Usage & Token Analytics', path: '/app/ai/usage', apiModule: 'analytics' },
  { key: 'knowledge-base-list', title: 'Knowledge Base List', path: '/app/knowledge', apiModule: 'knowledge' },
  { key: 'create-knowledge-base', title: 'Create Knowledge Base', path: '/app/knowledge/create', apiModule: 'knowledge' },
  { key: 'knowledge-entries-list', title: 'Knowledge Entries List', path: '/app/knowledge/:id/entries', apiModule: 'knowledge' },
  { key: 'create-knowledge-entry', title: 'Create Knowledge Entry', path: '/app/knowledge/:id/entries/create', apiModule: 'knowledge' },
  { key: 'edit-knowledge-entry', title: 'Edit Knowledge Entry', path: '/app/knowledge/:id/entries/:entryId/edit', apiModule: 'knowledge' },
  { key: 'automation-workflow-list', title: 'Automation Workflow List', path: '/app/automation/workflows', apiModule: 'automation' },
  { key: 'create-workflow', title: 'Create Workflow', path: '/app/automation/workflows/create', apiModule: 'automation' },
  { key: 'workflow-editor-embedded', title: 'Workflow Editor (Embedded)', path: '/app/automation/workflows/:id/editor', apiModule: 'automation' },
  { key: 'workflow-logs', title: 'Workflow Logs', path: '/app/automation/logs', apiModule: 'automation' },
  { key: 'contacts-list', title: 'Contacts List', path: '/app/contacts', apiModule: 'user' },
  { key: 'contact-detail', title: 'Contact Detail', path: '/app/contacts/:id', apiModule: 'user' },
  { key: 'import-contacts', title: 'Import Contacts', path: '/app/contacts/import', apiModule: 'user' },
  { key: 'export-contacts', title: 'Export Contacts', path: '/app/contacts/export', apiModule: 'user' },
  { key: 'broadcast-campaign-list', title: 'Broadcast Campaign List', path: '/app/campaigns', apiModule: 'messages' },
  { key: 'create-broadcast', title: 'Create Broadcast', path: '/app/campaigns/create', apiModule: 'messages' },
  { key: 'campaign-analytics', title: 'Campaign Analytics', path: '/app/campaigns/analytics', apiModule: 'analytics' },
  { key: 'message-analytics', title: 'Message Analytics', path: '/app/analytics/messages', apiModule: 'analytics' },
  { key: 'ai-analytics', title: 'AI Analytics', path: '/app/analytics/ai', apiModule: 'analytics' },
  { key: 'automation-analytics', title: 'Automation Analytics', path: '/app/analytics/automation', apiModule: 'analytics' },
  { key: 'agent-performance-analytics', title: 'Agent Performance Analytics', path: '/app/analytics/agents', apiModule: 'analytics' },
  { key: 'current-plan', title: 'Current Plan', path: '/app/billing/current-plan', apiModule: 'billing' },
  { key: 'upgrade-plan', title: 'Upgrade Plan', path: '/app/billing/upgrade', apiModule: 'subscription' },
  { key: 'usage-limits', title: 'Usage & Limits', path: '/app/billing/usage-limits', apiModule: 'subscription' },
  { key: 'invoice-history', title: 'Invoice History', path: '/app/billing/invoices', apiModule: 'billing' },
  { key: 'payment-methods', title: 'Payment Methods', path: '/app/billing/payment-methods', apiModule: 'billing' },
  { key: 'team-members-list', title: 'Team Members List', path: '/app/team/members', apiModule: 'user' },
  { key: 'invite-team-member', title: 'Invite Team Member', path: '/app/team/invite', apiModule: 'user' },
  { key: 'roles-permissions', title: 'Roles & Permissions', path: '/app/team/roles-permissions', apiModule: 'permissions' },
  { key: 'company-profile', title: 'Company Profile', path: '/app/settings/company-profile', apiModule: 'tenant' },
  { key: 'api-keys', title: 'API Keys', path: '/app/settings/api-keys', apiModule: 'tenant' },
  { key: 'webhook-settings', title: 'Webhook Settings', path: '/app/settings/webhooks', apiModule: 'webhook' },
  { key: 'security-settings', title: 'Security Settings', path: '/app/settings/security', apiModule: 'tenant' },
  { key: 'notifications-settings', title: 'Notifications Settings', path: '/app/settings/notifications', apiModule: 'tenant' },
] as const;
export const adminRoutes = [
  { key: 'platform-overview', title: 'Platform Overview', path: '/admin', apiModule: 'analytics' },
  { key: 'revenue-overview', title: 'Revenue Overview', path: '/admin/revenue', apiModule: 'billing' },
  { key: 'usage-overview', title: 'Usage Overview', path: '/admin/usage', apiModule: 'analytics' },
  { key: 'tenants-list', title: 'Tenants List', path: '/admin/tenants', apiModule: 'tenant' },
  { key: 'tenant-detail', title: 'Tenant Detail', path: '/admin/tenants/:id', apiModule: 'tenant' },
  { key: 'suspend-activate-tenant', title: 'Suspend / Activate Tenant', path: '/admin/tenants/:id/status', apiModule: 'tenant' },
  { key: 'tenant-usage-details', title: 'Tenant Usage Details', path: '/admin/tenants/:id/usage', apiModule: 'analytics' },
  { key: 'plans-management', title: 'Plans Management', path: '/admin/plans', apiModule: 'subscription' },
  { key: 'create-plan', title: 'Create Plan', path: '/admin/plans/create', apiModule: 'subscription' },
  { key: 'edit-plan', title: 'Edit Plan', path: '/admin/plans/:id/edit', apiModule: 'subscription' },
  { key: 'all-whatsapp-accounts', title: 'All WhatsApp Accounts', path: '/admin/whatsapp/accounts', apiModule: 'whatsapp' },
  { key: 'webhook-health-monitoring', title: 'Webhook Health Monitoring', path: '/admin/whatsapp/webhook-health', apiModule: 'webhook' },
  { key: 'ai-usage-overview', title: 'AI Usage Overview', path: '/admin/ai/usage', apiModule: 'analytics' },
  { key: 'token-consumption', title: 'Token Consumption', path: '/admin/ai/token-consumption', apiModule: 'analytics' },
  { key: 'cost-monitoring', title: 'Cost Monitoring', path: '/admin/ai/cost-monitoring', apiModule: 'billing' },
  { key: 'workflow-monitoring', title: 'Workflow Monitoring', path: '/admin/automation/monitoring', apiModule: 'automation' },
  { key: 'workflow-errors', title: 'Workflow Errors', path: '/admin/automation/errors', apiModule: 'automation' },
  { key: 'revenue-reports', title: 'Revenue Reports', path: '/admin/billing/revenue-reports', apiModule: 'billing' },
  { key: 'transaction-history', title: 'Transaction History', path: '/admin/billing/transactions', apiModule: 'billing' },
  { key: 'invoice-management', title: 'Invoice Management', path: '/admin/billing/invoices', apiModule: 'billing' },
  { key: 'platform-users-list', title: 'Platform Users List', path: '/admin/users', apiModule: 'user' },
  { key: 'admin-roles', title: 'Admin Roles', path: '/admin/users/admin-roles', apiModule: 'permissions' },
  { key: 'global-settings', title: 'Global Settings', path: '/admin/settings/global', apiModule: 'tenant' },
  { key: 'feature-flags', title: 'Feature Flags', path: '/admin/settings/feature-flags', apiModule: 'permissions' },
  { key: 'api-limits', title: 'API Limits', path: '/admin/settings/api-limits', apiModule: 'subscription' },
  { key: 'system-logs', title: 'System Logs', path: '/admin/settings/system-logs', apiModule: 'analytics' },
] as const;
export const allPlatformRoutes: readonly PageRoute[] = [...promotionalRoutes, ...tenantRoutes, ...adminRoutes];
